dbt_fusion_minimal:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth

      project: "{{ env_var('DBT_PROJECT_ID') }}"
      dataset: dbt_dev
      location: US

      threads: 4
      timeout_seconds: 300
      priority: interactive
